#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
   
provisioner:
  name: chef_zero
  environments_path: environments
  roles_path: roles
  client_rb:
    environment: development

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: test_w_common
    run_list:
      - role[w_common_role]
  - name: test_w_jenkins
    run_list:
      - role[w_common_role]
      - role[w_jenkins_role]